### ISSUE TITLE
pip install fails for pygame 2.0.1

### ISSUE THREAD

**Issue by NALStudio** [CribberSix/pygame-markdown#6]
pip gives this error when installing this.
```
ERROR: Could not find a version that satisfies the requirement pygame==1.9.6 (from pygame-markdown)
ERROR: No matching distribution found for pygame==1.9.6
```

Edit: `pip install pygame-markdown --no-dependencies` works.

**Comment by CribberSix** [comment]
I will have a look into it - I assumed the install instructions `pip install pygame==1.9.6` on [pypi.org](https://pypi.org/project/pygame/1.9.6/) would work, but I will test it.
