### ISSUE TITLE
feature request : collision match

### ISSUE THREAD

**Issue by pmp-p** [CribberSix/pygame-markdown#8]
While discussing pygbag use with teachers i came to an idea:

When rendering markup with python code inside would it be possible
to know if a ``` ````py ```` ```` code block is clicked and also get an ordered list of previous code blocks ?

my idea is to edit/run on click the concatenation of previous blocks up the one clicked in document  :
_______
### importing modules
```py
import pygame
pygame.init()
```
### init blah -blah
```py
# some init code
```
init blah -blah
### do stuff
```py
#some pygame example code
```

**Comment by CribberSix** [comment]
Theoretically: yes it would be possible by overlaying the code blocks with invisible buttons and storing the information of the code-block contents separately to execute them. However, this is way outside the scope of the  package to _"parse and render the contents of a markdown file onto a pygame surface"_.  You are welcome to fork the repository though and implement it.
